"use strict";

module.exports = {
  async up(queryInterface) {
    // specialty_id mapping:
    // 1=Médecine Générale, 2=Pédiatrie, 3=Cardiologie, 4=Dermatologie
    // 5=Gynécologie, 6=ORL, 7=Ophtalmologie, 8=Dentiste
    // 9=Psychiatrie, 10=Neurologie, 11=Orthopédie, 12=Urologie
    // 13=Gastro, 14=Pneumologie, 15=Chirurgie, 16=Endocrinologie
    // 17=Rhumatologie, 18=Néphrologie

    await queryInterface.bulkInsert("doctors", [
      // ── ALGER (12 doctors) ──────────────────────────────────────
      {
        user_id: 5,
        specialty_id: 1,
        doctor_name: "Dr. Fatima Zerrouki",
        clinic_name: "Cabinet Médical Zerrouki",
        clinic_address: "12 Rue Didouche Mourad, Alger Centre",
        wilaya: "Alger",
        commune: "Alger Centre",
        latitude: 36.73731,
        longitude: 3.08746,
        phone: "0661234501",
        whatsapp_number: "0661234501",
        consultation_fee: 1500.0,
        working_hours: JSON.stringify({
          monday: { morning: "08:00-12:00", afternoon: "14:00-18:00" },
          tuesday: { morning: "08:00-12:00", afternoon: "14:00-18:00" },
          wednesday: { morning: "08:00-12:00" },
          thursday: { morning: "08:00-12:00", afternoon: "14:00-18:00" },
          saturday: { morning: "09:00-13:00" },
        }),
        bio: "Médecin généraliste avec 15 ans d'expérience. Spécialisée dans la médecine préventive et le suivi des maladies chroniques.",
        years_of_experience: 15,
        average_rating: 4.8,
        total_reviews: 42,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: 6,
        specialty_id: 3,
        doctor_name: "Dr. Youcef Hadj",
        clinic_name: "Clinique Cardiologique El Hayat",
        clinic_address: "45 Boulevard Krim Belkacem, Alger",
        wilaya: "Alger",
        commune: "Hussein Dey",
        latitude: 36.745,
        longitude: 3.102,
        phone: "0772345678",
        whatsapp_number: "0772345678",
        consultation_fee: 3000.0,
        working_hours: JSON.stringify({
          monday: { morning: "09:00-13:00", afternoon: "15:00-19:00" },
          wednesday: { morning: "09:00-13:00", afternoon: "15:00-19:00" },
          thursday: { morning: "09:00-13:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Cardiologue interventionnel, ancien chef de service au CHU Mustapha. Expert en cardiologie du sport.",
        years_of_experience: 20,
        average_rating: 4.9,
        total_reviews: 87,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      /*
      {
        user_id: null,
        specialty_id: 2,
        doctor_name: "Dr. Samira Boukhelif",
        clinic_name: "Cabinet Pédiatrique Boukhelif",
        clinic_address: "8 Rue Ben M'Hidi, Bab El Oued",
        wilaya: "Alger",
        commune: "Bab El Oued",
        latitude: 36.783,
        longitude: 3.057,
        phone: "0551234502",
        whatsapp_number: "0551234502",
        consultation_fee: 1800.0,
        working_hours: JSON.stringify({
          monday: { morning: "08:30-12:30", afternoon: "14:30-18:30" },
          tuesday: { morning: "08:30-12:30", afternoon: "14:30-18:30" },
          thursday: { morning: "08:30-12:30", afternoon: "14:30-18:30" },
          saturday: { morning: "09:00-13:00" },
        }),
        bio: "Pédiatre spécialisée dans les maladies respiratoires de l'enfant et la néonatologie.",
        years_of_experience: 12,
        average_rating: 4.7,
        total_reviews: 56,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 4,
        doctor_name: "Dr. Anis Brahimi",
        clinic_name: "Dermatologie Esthétique Brahimi",
        clinic_address: "22 Rue Pasteur, Alger Centre",
        wilaya: "Alger",
        commune: "Alger Centre",
        latitude: 36.735,
        longitude: 3.091,
        phone: "0661234503",
        whatsapp_number: null,
        consultation_fee: 2500.0,
        working_hours: JSON.stringify({
          monday: { afternoon: "14:00-19:00" },
          tuesday: { afternoon: "14:00-19:00" },
          wednesday: { morning: "09:00-13:00", afternoon: "14:00-19:00" },
          thursday: { afternoon: "14:00-19:00" },
          saturday: { morning: "09:00-13:00" },
        }),
        bio: "Dermatologue et vénérologue. Spécialisé dans les dermatoses inflammatoires et la dermatologie esthétique.",
        years_of_experience: 10,
        average_rating: 4.6,
        total_reviews: 38,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 5,
        doctor_name: "Dr. Nadia Bensalem",
        clinic_name: "Cabinet Gynécologique Bensalem",
        clinic_address: "15 Cité les Pins, Ben Aknoun",
        wilaya: "Alger",
        commune: "Ben Aknoun",
        latitude: 36.756,
        longitude: 3.018,
        phone: "0771234503",
        whatsapp_number: "0771234503",
        consultation_fee: 2000.0,
        working_hours: JSON.stringify({
          monday: { morning: "09:00-12:00", afternoon: "15:00-18:00" },
          tuesday: { morning: "09:00-12:00", afternoon: "15:00-18:00" },
          wednesday: { morning: "09:00-12:00" },
          thursday: { morning: "09:00-12:00", afternoon: "15:00-18:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Gynécologue-obstétricienne. 18 ans d'expérience dans le suivi de grossesse et la gynécologie médicale.",
        years_of_experience: 18,
        average_rating: 4.9,
        total_reviews: 104,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 7,
        doctor_name: "Dr. Kamel Ouadah",
        clinic_name: "Centre Ophtalmologique Ouadah",
        clinic_address: "3 Rue Ahmed Bey, El Biar",
        wilaya: "Alger",
        commune: "El Biar",
        latitude: 36.767,
        longitude: 3.029,
        phone: "0551234504",
        whatsapp_number: "0551234504",
        consultation_fee: 2200.0,
        working_hours: JSON.stringify({
          monday: { morning: "08:00-13:00" },
          tuesday: { morning: "08:00-13:00", afternoon: "15:00-18:00" },
          thursday: { morning: "08:00-13:00", afternoon: "15:00-18:00" },
          saturday: { morning: "08:00-12:00" },
        }),
        bio: "Ophtalmologue spécialisé en chirurgie réfractive et pathologies rétiniennes.",
        years_of_experience: 14,
        average_rating: 4.7,
        total_reviews: 61,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 8,
        doctor_name: "Dr. Sihem Kaci",
        clinic_name: "Cabinet Dentaire Kaci",
        clinic_address: "7 Rue Abane Ramdane, Kouba",
        wilaya: "Alger",
        commune: "Kouba",
        latitude: 36.712,
        longitude: 3.098,
        phone: "0661234505",
        whatsapp_number: "0661234505",
        consultation_fee: 1500.0,
        working_hours: JSON.stringify({
          monday: { morning: "09:00-13:00", afternoon: "14:00-18:00" },
          tuesday: { morning: "09:00-13:00", afternoon: "14:00-18:00" },
          wednesday: { morning: "09:00-13:00" },
          thursday: { morning: "09:00-13:00", afternoon: "14:00-18:00" },
          saturday: { morning: "09:00-13:00" },
        }),
        bio: "Chirurgien dentiste spécialisé en orthodontie et implantologie.",
        years_of_experience: 9,
        average_rating: 4.5,
        total_reviews: 29,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 10,
        doctor_name: "Dr. Rachid Ferhat",
        clinic_name: "Neurologie Ferhat",
        clinic_address: "31 Boulevard Mohamed V, Hydra",
        wilaya: "Alger",
        commune: "Hydra",
        latitude: 36.748,
        longitude: 3.032,
        phone: "0771234504",
        whatsapp_number: null,
        consultation_fee: 3200.0,
        working_hours: JSON.stringify({
          monday: { afternoon: "15:00-19:00" },
          wednesday: { afternoon: "15:00-19:00" },
          thursday: { morning: "09:00-13:00", afternoon: "15:00-19:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Neurologue, spécialiste des maladies neurodégénératives et épilepsie. Ancien résident au CHU de Genève.",
        years_of_experience: 22,
        average_rating: 4.8,
        total_reviews: 73,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 11,
        doctor_name: "Dr. Mourad Belaid",
        clinic_name: "Cabinet Orthopédique Belaid",
        clinic_address: "19 Rue Larbi Ben M'Hidi, Alger",
        wilaya: "Alger",
        commune: "Alger Centre",
        latitude: 36.739,
        longitude: 3.084,
        phone: "0551234506",
        whatsapp_number: "0551234506",
        consultation_fee: 2800.0,
        working_hours: JSON.stringify({
          tuesday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          wednesday: { morning: "09:00-13:00" },
          thursday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Chirurgien orthopédiste spécialisé dans la chirurgie du genou et de la hanche. Techniques mini-invasives.",
        years_of_experience: 17,
        average_rating: 4.6,
        total_reviews: 44,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 13,
        doctor_name: "Dr. Leila Meziane",
        clinic_name: "Gastro-entérologie Meziane",
        clinic_address: "5 Cité Belouizdad, Belouizdad",
        wilaya: "Alger",
        commune: "Belouizdad",
        latitude: 36.726,
        longitude: 3.078,
        phone: "0661234507",
        whatsapp_number: "0661234507",
        consultation_fee: 2500.0,
        working_hours: JSON.stringify({
          monday: { morning: "09:00-13:00", afternoon: "14:30-18:30" },
          tuesday: { morning: "09:00-13:00" },
          thursday: { morning: "09:00-13:00", afternoon: "14:30-18:30" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Gastro-entérologue et hépatologue. Spécialisée dans les maladies inflammatoires de l'intestin.",
        years_of_experience: 13,
        average_rating: 4.7,
        total_reviews: 52,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 14,
        doctor_name: "Dr. Hamid Bouzid",
        clinic_name: "Cabinet Pneumologique Bouzid",
        clinic_address: "28 Rue des Frères Bouadou, Bir Mourad Raïs",
        wilaya: "Alger",
        commune: "Bir Mourad Raïs",
        latitude: 36.721,
        longitude: 3.065,
        phone: "0771234505",
        whatsapp_number: null,
        consultation_fee: 2200.0,
        working_hours: JSON.stringify({
          monday: { morning: "08:30-12:30", afternoon: "14:00-17:30" },
          wednesday: { morning: "08:30-12:30", afternoon: "14:00-17:30" },
          thursday: { morning: "08:30-12:30" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Pneumologue spécialisé dans l'asthme, la BPCO et les maladies respiratoires professionnelles.",
        years_of_experience: 16,
        average_rating: 4.5,
        total_reviews: 35,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 9,
        doctor_name: "Dr. Sara Mekki",
        clinic_name: "Cabinet de Psychiatrie Mekki",
        clinic_address: "11 Rue Hassiba Ben Bouali, Alger",
        wilaya: "Alger",
        commune: "Alger Centre",
        latitude: 36.732,
        longitude: 3.089,
        phone: "0551234508",
        whatsapp_number: "0551234508",
        consultation_fee: 3000.0,
        working_hours: JSON.stringify({
          monday: { afternoon: "14:00-19:00" },
          tuesday: { afternoon: "14:00-19:00" },
          wednesday: { afternoon: "14:00-19:00" },
          thursday: { afternoon: "14:00-19:00" },
        }),
        bio: "Psychiatre spécialisée en thérapies cognitivo-comportementales et troubles anxieux.",
        years_of_experience: 11,
        average_rating: 4.9,
        total_reviews: 28,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ── ORAN (5 doctors) ────────────────────────────────────────
      {
        user_id: null,
        specialty_id: 1,
        doctor_name: "Dr. Mohamed Tlemcani",
        clinic_name: "Cabinet Médical Tlemcani",
        clinic_address: "14 Rue Khemisti, Oran",
        wilaya: "Oran",
        commune: "Oran",
        latitude: 35.69694,
        longitude: -0.6302,
        phone: "0661234510",
        whatsapp_number: "0661234510",
        consultation_fee: 1500.0,
        working_hours: JSON.stringify({
          monday: { morning: "08:00-12:00", afternoon: "14:00-18:00" },
          tuesday: { morning: "08:00-12:00", afternoon: "14:00-18:00" },
          thursday: { morning: "08:00-12:00", afternoon: "14:00-18:00" },
          saturday: { morning: "09:00-13:00" },
        }),
        bio: "Médecin généraliste avec expertise en médecine du travail et maladies chroniques.",
        years_of_experience: 14,
        average_rating: 4.6,
        total_reviews: 47,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 3,
        doctor_name: "Dr. Amira Benzerga",
        clinic_name: "Cardiologie Benzerga",
        clinic_address: "8 Boulevard Millénium, Oran",
        wilaya: "Oran",
        commune: "Oran",
        latitude: 35.701,
        longitude: -0.645,
        phone: "0771234510",
        whatsapp_number: "0771234510",
        consultation_fee: 2800.0,
        working_hours: JSON.stringify({
          monday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          wednesday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          thursday: { morning: "09:00-13:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Cardiologue avec fellowship en échocardiographie. Prise en charge des insuffisances cardiaques.",
        years_of_experience: 16,
        average_rating: 4.8,
        total_reviews: 63,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 5,
        doctor_name: "Dr. Houria Benkhelil",
        clinic_name: "Cabinet Gynécologique Benkhelil",
        clinic_address: "25 Rue des Aurès, Oran",
        wilaya: "Oran",
        commune: "Oran",
        latitude: 35.692,
        longitude: -0.628,
        phone: "0551234511",
        whatsapp_number: "0551234511",
        consultation_fee: 2000.0,
        working_hours: JSON.stringify({
          monday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          tuesday: { morning: "09:00-13:00" },
          wednesday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Gynécologue spécialisée en endoscopie gynécologique et prise en charge de l'infertilité.",
        years_of_experience: 12,
        average_rating: 4.7,
        total_reviews: 51,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 8,
        doctor_name: "Dr. Farid Mekhloufi",
        clinic_name: "Cabinet Dentaire Mekhloufi",
        clinic_address: "3 Cité Boulanger, Oran",
        wilaya: "Oran",
        commune: "Oran",
        latitude: 35.705,
        longitude: -0.651,
        phone: "0661234512",
        whatsapp_number: null,
        consultation_fee: 1500.0,
        working_hours: JSON.stringify({
          monday: { morning: "09:00-13:00", afternoon: "14:00-18:00" },
          tuesday: { morning: "09:00-13:00", afternoon: "14:00-18:00" },
          thursday: { morning: "09:00-13:00", afternoon: "14:00-18:00" },
          saturday: { morning: "09:00-13:00" },
        }),
        bio: "Chirurgien dentiste, spécialiste en prothèses dentaires et chirurgie maxillo-faciale.",
        years_of_experience: 8,
        average_rating: 4.4,
        total_reviews: 22,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 2,
        doctor_name: "Dr. Nassim Benbrahim",
        clinic_name: "Pédiatrie Benbrahim",
        clinic_address: "17 Rue de la Paix, Oran",
        wilaya: "Oran",
        commune: "Oran",
        latitude: 35.698,
        longitude: -0.635,
        phone: "0771234511",
        whatsapp_number: "0771234511",
        consultation_fee: 1800.0,
        working_hours: JSON.stringify({
          monday: { morning: "08:30-12:30", afternoon: "14:30-18:00" },
          tuesday: { morning: "08:30-12:30", afternoon: "14:30-18:00" },
          thursday: { morning: "08:30-12:30", afternoon: "14:30-18:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Pédiatre généraliste, suivi de croissance et vaccination. Urgences pédiatriques.",
        years_of_experience: 10,
        average_rating: 4.6,
        total_reviews: 39,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ── CONSTANTINE (4 doctors) ────────────────────────────────
      {
        user_id: null,
        specialty_id: 1,
        doctor_name: "Dr. Abdelkader Guechtouli",
        clinic_name: "Cabinet Guechtouli",
        clinic_address: "6 Rue Larbi Ben M'Hidi, Constantine",
        wilaya: "Constantine",
        commune: "Constantine",
        latitude: 36.365,
        longitude: 6.61472,
        phone: "0551234520",
        whatsapp_number: "0551234520",
        consultation_fee: 1500.0,
        working_hours: JSON.stringify({
          monday: { morning: "08:00-12:00", afternoon: "14:00-18:00" },
          tuesday: { morning: "08:00-12:00", afternoon: "14:00-18:00" },
          wednesday: { morning: "08:00-12:00" },
          thursday: { morning: "08:00-12:00", afternoon: "14:00-18:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Médecin généraliste. Prise en charge du diabète, hypertension et maladies métaboliques.",
        years_of_experience: 19,
        average_rating: 4.7,
        total_reviews: 58,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 11,
        doctor_name: "Dr. Sofiane Rahmani",
        clinic_name: "Orthopédie Rahmani",
        clinic_address: "20 Avenue Belouizdad, Constantine",
        wilaya: "Constantine",
        commune: "Constantine",
        latitude: 36.368,
        longitude: 6.618,
        phone: "0661234521",
        whatsapp_number: null,
        consultation_fee: 2800.0,
        working_hours: JSON.stringify({
          tuesday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          wednesday: { morning: "09:00-13:00" },
          thursday: { afternoon: "15:00-18:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Chirurgien orthopédiste, spécialiste des traumatismes sportifs et chirurgie rachidienne.",
        years_of_experience: 15,
        average_rating: 4.5,
        total_reviews: 31,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 4,
        doctor_name: "Dr. Wafa Chebira",
        clinic_name: "Dermatologie Chebira",
        clinic_address: "9 Rue Zighoud Youcef, Constantine",
        wilaya: "Constantine",
        commune: "Constantine",
        latitude: 36.362,
        longitude: 6.609,
        phone: "0771234520",
        whatsapp_number: "0771234520",
        consultation_fee: 2000.0,
        working_hours: JSON.stringify({
          monday: { afternoon: "14:00-18:30" },
          tuesday: { afternoon: "14:00-18:30" },
          wednesday: { morning: "09:00-13:00", afternoon: "14:00-18:30" },
          thursday: { afternoon: "14:00-18:30" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Dermatologue spécialisée dans les maladies cutanées allergiques et cosmétologie médicale.",
        years_of_experience: 9,
        average_rating: 4.6,
        total_reviews: 27,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 6,
        doctor_name: "Dr. Tarek Boussaha",
        clinic_name: "ORL Boussaha",
        clinic_address: "33 Cité Daksi, Constantine",
        wilaya: "Constantine",
        commune: "Constantine",
        latitude: 36.371,
        longitude: 6.623,
        phone: "0551234522",
        whatsapp_number: "0551234522",
        consultation_fee: 2200.0,
        working_hours: JSON.stringify({
          monday: { morning: "09:00-13:00" },
          tuesday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          thursday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "ORL spécialisé en otologie, rhinologie et chirurgie cervico-faciale.",
        years_of_experience: 12,
        average_rating: 4.4,
        total_reviews: 19,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ── ANNABA (3 doctors) ─────────────────────────────────────
      {
        user_id: null,
        specialty_id: 1,
        doctor_name: "Dr. Nawel Bensaci",
        clinic_name: "Cabinet Médical Bensaci",
        clinic_address: "4 Rue du 1er Novembre, Annaba",
        wilaya: "Annaba",
        commune: "Annaba",
        latitude: 36.903,
        longitude: 7.753,
        phone: "0661234530",
        whatsapp_number: "0661234530",
        consultation_fee: 1500.0,
        working_hours: JSON.stringify({
          monday: { morning: "08:00-12:00", afternoon: "14:00-17:30" },
          tuesday: { morning: "08:00-12:00", afternoon: "14:00-17:30" },
          thursday: { morning: "08:00-12:00", afternoon: "14:00-17:30" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Médecin généraliste. Consultation urgences et soins primaires.",
        years_of_experience: 8,
        average_rating: 4.3,
        total_reviews: 14,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 16,
        doctor_name: "Dr. Samir Laraba",
        clinic_name: "Endocrinologie Laraba",
        clinic_address: "12 Cité El Bouni, Annaba",
        wilaya: "Annaba",
        commune: "El Bouni",
        latitude: 36.898,
        longitude: 7.749,
        phone: "0771234530",
        whatsapp_number: null,
        consultation_fee: 2500.0,
        working_hours: JSON.stringify({
          monday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          wednesday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Endocrinologue spécialisé dans le diabète, les maladies thyroïdiennes et l'obésité.",
        years_of_experience: 13,
        average_rating: 4.7,
        total_reviews: 33,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 15,
        doctor_name: "Dr. Redha Cheniti",
        clinic_name: "Chirurgie Générale Cheniti",
        clinic_address: "7 Boulevard de l'ALN, Annaba",
        wilaya: "Annaba",
        commune: "Annaba",
        latitude: 36.905,
        longitude: 7.757,
        phone: "0551234531",
        whatsapp_number: "0551234531",
        consultation_fee: 3000.0,
        working_hours: JSON.stringify({
          tuesday: { morning: "09:00-13:00" },
          wednesday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          thursday: { morning: "09:00-13:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Chirurgien général spécialisé en chirurgie laparoscopique et chirurgie digestive.",
        years_of_experience: 20,
        average_rating: 4.8,
        total_reviews: 46,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ── TLEMCEN (3 doctors) ────────────────────────────────────
      {
        user_id: null,
        specialty_id: 1,
        doctor_name: "Dr. Billal Hadjadj",
        clinic_name: "Cabinet Hadjadj",
        clinic_address: "18 Rue Colonel Lotfi, Tlemcen",
        wilaya: "Tlemcen",
        commune: "Tlemcen",
        latitude: 34.87833,
        longitude: -1.31667,
        phone: "0661234540",
        whatsapp_number: "0661234540",
        consultation_fee: 1500.0,
        working_hours: JSON.stringify({
          monday: { morning: "08:00-12:00", afternoon: "14:00-17:30" },
          tuesday: { morning: "08:00-12:00", afternoon: "14:00-17:30" },
          thursday: { morning: "08:00-12:00", afternoon: "14:00-17:30" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Médecin généraliste, spécialiste en médecine interne et maladies infectieuses.",
        years_of_experience: 11,
        average_rating: 4.5,
        total_reviews: 24,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 17,
        doctor_name: "Dr. Fateh Belkaid",
        clinic_name: "Rhumatologie Belkaid",
        clinic_address: "5 Rue de la République, Tlemcen",
        wilaya: "Tlemcen",
        commune: "Tlemcen",
        latitude: 34.876,
        longitude: -1.314,
        phone: "0771234540",
        whatsapp_number: "0771234540",
        consultation_fee: 2500.0,
        working_hours: JSON.stringify({
          monday: { afternoon: "15:00-18:30" },
          wednesday: { morning: "09:00-13:00", afternoon: "15:00-18:30" },
          thursday: { afternoon: "15:00-18:30" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Rhumatologue spécialisé dans la polyarthrite rhumatoïde et les spondylarthropathies.",
        years_of_experience: 14,
        average_rating: 4.6,
        total_reviews: 29,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 12,
        doctor_name: "Dr. Yasmina Ghali",
        clinic_name: "Urologie Ghali",
        clinic_address: "22 Cité Bel Air, Tlemcen",
        wilaya: "Tlemcen",
        commune: "Tlemcen",
        latitude: 34.879,
        longitude: -1.319,
        phone: "0551234541",
        whatsapp_number: null,
        consultation_fee: 2800.0,
        working_hours: JSON.stringify({
          tuesday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          thursday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Urologue spécialisée dans les pathologies urinaires féminines et masculine. Chirurgie laparoscopique.",
        years_of_experience: 10,
        average_rating: 4.7,
        total_reviews: 21,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },

      // ── SÉTIF (3 doctors) ──────────────────────────────────────
      {
        user_id: null,
        specialty_id: 1,
        doctor_name: "Dr. Omar Boudjemaa",
        clinic_name: "Cabinet Boudjemaa",
        clinic_address: "10 Rue de l'Indépendance, Sétif",
        wilaya: "Sétif",
        commune: "Sétif",
        latitude: 36.19112,
        longitude: 5.41373,
        phone: "0661234550",
        whatsapp_number: "0661234550",
        consultation_fee: 1500.0,
        working_hours: JSON.stringify({
          monday: { morning: "08:00-12:00", afternoon: "14:00-18:00" },
          tuesday: { morning: "08:00-12:00", afternoon: "14:00-18:00" },
          thursday: { morning: "08:00-12:00", afternoon: "14:00-18:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Médecin généraliste. Suivi des pathologies chroniques et médecine de famille.",
        years_of_experience: 16,
        average_rating: 4.4,
        total_reviews: 37,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 18,
        doctor_name: "Dr. Chahra Bencherif",
        clinic_name: "Néphrologie Bencherif",
        clinic_address: "3 Boulevard Maâouia, Sétif",
        wilaya: "Sétif",
        commune: "Sétif",
        latitude: 36.193,
        longitude: 5.418,
        phone: "0771234550",
        whatsapp_number: null,
        consultation_fee: 2800.0,
        working_hours: JSON.stringify({
          monday: { morning: "09:00-13:00" },
          wednesday: { morning: "09:00-13:00", afternoon: "15:00-18:00" },
          thursday: { afternoon: "15:00-18:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Néphrologue spécialisée dans l'insuffisance rénale chronique et le suivi des dialysés.",
        years_of_experience: 12,
        average_rating: 4.6,
        total_reviews: 18,
        is_verified: true,
        created_at: new Date(),
        updated_at: new Date(),
      },
      {
        user_id: null,
        specialty_id: 7,
        doctor_name: "Dr. Idir Amrani",
        clinic_name: "Ophtalmologie Amrani",
        clinic_address: "16 Rue Amirouche, Sétif",
        wilaya: "Sétif",
        commune: "Sétif",
        latitude: 36.19,
        longitude: 5.411,
        phone: "0551234551",
        whatsapp_number: "0551234551",
        consultation_fee: 2000.0,
        working_hours: JSON.stringify({
          monday: { morning: "09:00-13:00", afternoon: "14:30-18:00" },
          tuesday: { morning: "09:00-13:00" },
          thursday: { morning: "09:00-13:00", afternoon: "14:30-18:00" },
          saturday: { morning: "09:00-12:00" },
        }),
        bio: "Ophtalmologue, spécialiste du glaucome et de la dégénérescence maculaire.",
        years_of_experience: 7,
        average_rating: 4.3,
        total_reviews: 15,
        is_verified: false,
        created_at: new Date(),
        updated_at: new Date(),
      },
      */
    ]);
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete("doctors", null, {});
  },
};
